server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://mysql:3306/digital_wallet
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkeymysecretkeymysecretkey123456
  expiration: 86400000
  refresh-expiration: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs