#
#  server:
#    port: 8085
#
#  spring:
#    application:
#      name: API-GATEWAY
#
#    cloud:
#      gateway:
#        routes:
#
#          - id: auth-service
#            uri: lb://AUTH-SERVICE
#            predicates:
#              - Path=/auth/**
#
#          - id: action-service
#            uri: lb://ACTION-SERVICE
#            predicates:
#              - Path=/action/**
#
#          - id: query-service
#            uri: lb://QUERY-SERVICE
#            predicates:
#              - Path=/query/**
#
#          - id: ledger-service
#            uri: lb://LEDGER-SERVICE
#            predicates:
#              - Path=/ledger/**
#
##  Eureka
#  eureka:
#    client:
#      service-url:
#        defaultZone: http://localhost:8761/eureka/
#    instance:
#      prefer-ip-address: true
#
#  jwt:
#    secret: mysecretkeymysecretkeymysecretkey123456
#    expiration: 86400000
#
#  management:
#    endpoints:
#      web:
#        exposure:
#          include: "*"
#


server:
  port: 8085

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:

      default-filters:
        - name: Retry
          args:
            retries: 2
            statuses:
              - BAD_GATEWAY
              - SERVICE_UNAVAILABLE
              - GATEWAY_TIMEOUT
            methods:
              - GET,POST,PATCH,PUT,DELETE

      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: action-service
          uri: lb://ACTION-SERVICE
          predicates:
            - Path=/action/**
          filters:
            - name: CircuitBreaker
              args:
                name: actionCircuitBreaker
                fallbackUri: forward:/fallback/action

        - id: query-service
          uri: lb://QUERY-SERVICE
          predicates:
            - Path=/query/**
          filters:
            - name: CircuitBreaker
              args:
                name: queryCircuitBreaker
                fallbackUri: forward:/fallback/query

        - id: ledger-service
          uri: lb://LEDGER-SERVICE
          predicates:
            - Path=/ledger/**
          filters:
            - name: CircuitBreaker
              args:
                name: ledgerCircuitBreaker
                fallbackUri: forward:/fallback/ledger

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

jwt:
  secret: mysecretkeymysecretkeymysecretkey123456
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:

      authCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      actionCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      queryCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      ledgerCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
