package com.example.Query_Service.dto.ai;

public enum AiIntent {

    // Transaction Queries
    LAST_TRANSACTION,
    LAST_N_TRANSACTIONS,
    MINI_STATEMENT,
    TRANSACTION_BY_REFERENCE,
    TRANSACTIONS_BY_STATUS,
    TRANSACTIONS_BY_TYPE,
    TRANSACTIONS_BY_DATE_RANGE,
    TRANSACTIONS_BY_AMOUNT_RANGE,
    ALL_TRANSACTIONS,

    // Deposit Queries
    ALL_DEPOSITS,
    DEPOSITS_BY_STATUS,
    DEPOSITS_BY_DATE_RANGE,
    DEPOSITS_BY_AMOUNT_RANGE,

    // Withdraw Queries
    ALL_WITHDRAWALS,
    WITHDRAWALS_BY_STATUS,
    WITHDRAWALS_BY_DATE_RANGE,
    WITHDRAWALS_BY_AMOUNT_RANGE,

    // Dashboard
    DASHBOARD,
    ACCOUNT_DASHBOARD,

    // Account
    ACCOUNT_DETAILS,
    BALANCE,

    // QR
    QR_LOOKUP,

    // Split Bill
    SPLIT_BILL_DETAILS,
    SPLIT_BILL_SUMMARY,
    SPLIT_BILL_PARTICIPANTS,
    CREATED_SPLIT_BILLS,
    PENDING_SPLIT_BILLS,

    UNKNOWN
}