server:
  port: 8083

spring:
  application:
    name: LEDGER-SERVICE

  datasource:
    url: jdbc:mysql://mysql:3306/digital_wallet
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs