name: Digital Wallet CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # Build every microservice
      - name: Build Auth-Service
        working-directory: Auth-Service
        run: mvn clean install -DskipTests

      - name: Build Action-Service
        working-directory: Action-Service
        run: mvn clean install -DskipTests

      - name: Build Ledger-Service
        working-directory: Ledger-Service
        run: mvn clean install -DskipTests

      - name: Build Query-Service
        working-directory: Query-Service
        run: mvn clean install -DskipTests

      - name: Build Notification-Service
        working-directory: Notification-Service
        run: mvn clean install -DskipTests

      - name: Build Kyc-Service
        working-directory: Kyc-Service
        run: mvn clean install -DskipTests

      - name: Build Api-Gateway
        working-directory: Api-Gateway
        run: mvn clean install -DskipTests

      # SonarCloud Analysis
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -f Action-Service/pom.xml \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=lokeshkhadse \
          -Dsonar.projectKey=Lokeshkhadse_Digital-Wallet-UPI \
          -Dsonar.token=${SONAR_TOKEN}